# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://pants.readme.io/docs/using-pants-in-ci for tips on how to set up your CI with Pants.

env:
  global:
    - PANTS_CONFIG_FILES=pants.ci.toml

os: linux
dist: bionic
language: python
python: 3.7
notifications:
  webhooks:
    urls:
      -  https://staging.webhooks.toolchain.com/travis/repo/toolchainlabs/example-python/
    on_success: always
    on_failure: always
    on_start:   always
    on_cancel:  always
    on_error:   always
cache:
  directories:
    - $HOME/.cache/pants/setup
    - $HOME/.cache/pants/lmdb_store

install:
  - ./pants --version  # This will bootstrap Pants

script:
  # We also smoke test that our release process will work by running `package`.
  - ./pants lint typecheck test package '::'
  - ./pants run helloworld/main.py
  - ./pants run helloworld/main_py2.py
